### ISSUE TITLE
думаю тут должно быть выборка из таблицы сорсов

### ISSUE THREAD

**Issue by Kirill-Shkodkin** [EliriaT/go-tasks#2]
https://github.com/EliriaT/go-tasks/blob/df56e181d8ac884d23343853a1d04aed6eb1b18a/db/models/source.go#L56

**Comment by EliriaT** [comment]
Yes, thank you, fixed now 
https://github.com/EliriaT/go-tasks/commit/9125e914062b5c0f59b767aca363d17a44979e67
